version: '3'
services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27028:27017"

volumes:
  mongodb_data: